[package]
name = "cower-rs"
version = "0.1.0"
authors = ["Brandon Mittman <brandonmittman@gmail.com>"]

[profile.release]
panic = 'abort'
lto = true

[dependencies]
clap         = "*"
time         = "*"
bitmask      = "*"
isatty       = "*"
stderrlog    = "*"
log          = "*"
ferris-says  = "*"
